'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''lblHarwareOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHarwareOpen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHarInProc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHarInProc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHarPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHarPending As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHardSolved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHardSolved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHardClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHardClosed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComHardware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComHardware As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoftwareOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoftwareOpen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoftInProc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoftInProc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoftPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoftPending As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoftSolved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoftSolved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSoftClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoftClosed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComSoftware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComSoftware As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNetworkOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetworkOpen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNetInProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetInProcess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNetPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetPending As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNetSolved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetSolved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNetClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetClosed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNetwork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNetwork As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInprocess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInprocess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPending As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSolved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolved As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblClosed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClosed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalRecords As Global.System.Web.UI.WebControls.Label
End Class
